services:
  mongo:
    image: mongo
    container_name: mongodb-container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: sadikshya
      MONGO_INITDB_ROOT_PASSWORD: SuperSecurePassword
    ports:
      - 27017:27017
